version: 2

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: docs/requirements.txt
    - requirements: requirements.txt
    - method: setuptools
      path: .
