version: 2
formats: []
build:
  image: stable
python:
  version: 3.8
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false