version: '2.1'

services:

  postgres:
    image: kartoza/postgis:13-3.1
    environment:
      POSTGRES_PASSWORD: 'db_builder'
      POSTGRES_USER: 'builder'
      POSTGRES_DB: 'test'
      TZ: 'US/Mountain'
      PGTZ: 'US/Mountain'
    ports:
      - 5432:5432
    healthcheck:
      test: "exit 0"
